### ISSUE TITLE
private ssh key

### ISSUE THREAD

**Issue by lysium** [hiroolie/chef-repo#1]
Your private ssh key is published here on github. Don't know if this is intentional.

**Comment by hiroolie** [comment]
I'm sorry. The security was not aware of . The subject of the file has already been removed from the repository .

**Comment by lysium** [comment]
I suggest that you change your keys, as they are still visible here https://github.com/hiroolie/chef-repo/commit/d524daa659900c649c2fbbcaf5f43794edc5f1fd
